### ISSUE TITLE
Release tarball lacks configure script

### ISSUE THREAD

**Issue by rkeene** [flightaware/tclreadline#13]
Release tarball (obtained from https://github.com/flightaware/tclreadline/releases/tag/v2.3.2 ) does not contain a configure script.  The documentation (README.md and INSTALL) included with this release tarball indicates that it should.  It's also pretty standard for release tarballs to include a configure script, especially ones that use the GNU autoconf or GNU automake system.

**Comment by resuna** [comment]
The configure script is generated from configure.ac by autoconf.

**Comment by rkeene** [comment]
From what the documentation indicates, it should be already generated and included in the release tarball.

**Comment by resuna** [comment]
Obviously a documentation bug, will fix.

It's pretty unusual to ship generated files... most packages that do have it there for legacy reasons. After all, they will almost certainly have been generated on a different platform and need to be regenerated anyway.

**Comment by rkeene** [comment]
The configure script is generated and included with a release tarball in 10,000+ other packages.  It's very common to include it.  It's also probably a good idea to include it.

**Comment by resuna** [comment]
It's a bad idea, since it will need to be recreated anyway, but I have committed a version created with the libtool/autoconf toolchain for Ubuntu Linux. I will cut a new release.

**Comment by rkeene** [comment]
I've compiled things with release-engineering generated configure scripts across dozens of platforms and never had to regenerate the configure script (on Solaris, HP-UX, FreeBSD, OpenBSD, NetBSD, Linux, Minix, IRIX, AIX).  I don't know under what conditions the release-engineering generated configure script would need to be regenerated, but it's something exotic.

**Comment by bovine** [comment]
v2.3.4 has been tagged with a configure script in it.
https://github.com/flightaware/tclreadline/releases/tag/v2.3.4

**Comment by rkeene** [comment]
Thanks !
