### ISSUE TITLE
Dangling symlinks in the aux/ dir

### ISSUE THREAD

**Issue by sgolovan** [flightaware/tclreadline#14]
Currently, v2.3.5 and the master branch contain symlinks in aux/ which point outside the build tree (aux/compile -> /usr/share/automake-1.15/compile etc.).

The issue is similar to #7.

Could you replace the symlinks by their targets once more?

**Comment by resuna** [comment]
I didn't notice that, sorry. I'll try finding a machine where autoconf doesn't do that. Apparently that's an Ubuntu thing. In the meantime you can run autoconf to rebuild the files.

I really want to leave all those generated files out and require autoconf, see https://github.com/flightaware/tclreadline/issues/13 .

**Comment by bovine** [comment]
fixed by above
