### ISSUE TITLE
Release tarball for v2.3.5 lacks Makefile.in

### ISSUE THREAD

**Issue by rkeene** [flightaware/tclreadline#16]

**Comment by reedjosh** [comment]
I worked around the missing makefile.in by rebuilding the conf tools. For my situation and likely for most people, this would be necessary as the given makefile.in wouldn't have been sufficient anyway.

The following aren't the exact steps, but should get you moving.

autoreconf --force --install
automake
./configure
...

**Comment by JohnLunzer** [comment]
@reedjosh thank you for this, I ran into this problem myself

**Comment by snoe925** [comment]
v2.3.8 should fix this
