### ISSUE TITLE
stub support available or missing?

### ISSUE THREAD

**Issue by jghub** [flightaware/tclreadline#29]
I am on OSX and using tclreadline installed by the package management system (macports). it has transpired that this tclreadline then only works together with the tclsh linked against the same libtcl8.6.a but memfaults when trying to use it with a differently compiled tclsh (even if same patchlevel, here 8.6.10).
I have been told on comp.lang.tcl that the issue is missing "stub support". the macports package maintainer does not see any configure flag to activate it.

my question: can it be done (ie. tclreadline compiled with stubs enabled so that libtcl is only selected at runtime)? if so, how?

**Comment by snoe925** [comment]
Stub support was added in v2.3.7
```
NOCONFIGURE=1 ./autogen.sh
./configure --enable-tclstub
make
```
On a modern OS X I am having a great deal of problems with automake working.  Also, this installer writes a path into tclreadlineInit.tcl.  A modern extension would not pre-process the tcl script.

That said there is no CI building on OS X.  We need CI builds for OS X contributed.

There are a lot of build traps in OS X.  The OS X readine library and headers are actually the getline library in "compatibility" mode with an ancient readline header. The tcl is typically 8.5 from the OS X install.

Therefore, I build libreadline.a as static library.  Then I had to skip over the automake building and manually compile and install.

```
mkdir build && cd build
git clone https://git.savannah.gnu.org/git/readline.git
git clone https://github.com/flightaware/tclreadline.git
cd readline
./configure --disable-shared --enable-static
make
cd ../tclreadline
git checkout v2.3.8
NOCONFIGURE=1 ./autogen.sh
# Your with-tcl parameter will vary
./configure --enable-tclstub --with-readline-includes=../readline --with-readline-library=../readline/libreadline.a --with-tcl=/usr/local/lib/tcl8.6
# do not run make as autoconf is still broken
# use xcrun and skip the gcc fake wrappers on OS X
# you have to install the Xcode command line tools
xcrun cc -DUSE_TCL_STUBS -dynamiclib -I. -I..  -o libtclreadline.dylib tclreadline.c /usr/local/lib/libtclstub8.6.a ../readline/libreadline.a -lpthread -lc -lncurses
# manually install
mkdir /usr/local/lib/tclreadline2.3.8
# check/fix the install path by editing this file which configure created
vi tclreadlineInit.tcl
cp libtclreadline.dylib /usr/local/lib/tclreadline2.3.8
cp tclreadline*.tcl /usr/local/lib/tclreadline2.3.8
```

**Comment by snoe925** [comment]
If you just want a tclsh that works with tclreadline.  I would recommend just using tclsh from miniconda.
https://docs.conda.io/en/latest/miniconda.html
https://anaconda.org/conda-forge/tclreadline

**Comment by jghub** [comment]
thanks a lot for this clarification. not sure, yet, whether I completely get the details.but we'll see :).
ideally, of course, the macports people should be able to change the build procedure for tclreadline to use stubs so that the average user (like me) can stick with installation via the package manager and _still_ access the tclreadline from different tclsh incarnations. I have asked them now whether this would be possible etc.

**Comment by bovine** [comment]
Closing, since `Stub support was added in v2.3.7`
