### ISSUE TITLE
Use --prefix=/usr/local will cause the following problem: can't find package tclreadline.

### ISSUE THREAD

**Issue by hongyi-zhao** [flightaware/tclreadline#33]
On Ubuntu 20.10, I try to compile and install the latest git master version of tclreadline as shown below:

```
$ sudo apt-get build-dep -y tcl-tclreadline
$ git clone https://github.com/flightaware/tclreadline.git tclreadline.git
$ cd tclreadline.git
$ ./configure --prefix=/usr/local --enable-tclshrl --enable-wishrl
$ make
$ sudo make install
```
Then I set the `$HOME/.tclshrc` as noted [here](https://github.com/flightaware/tclreadline#using-tclreadline-for-interactive-tcl-scripting), but when I start tclsh, it will complain about the following problem:
```
$ tclsh
can't find package tclreadline
%
```
OTOH, it I don't use `--prefix=/usr/local`, the problem will be fixed. Any hints for this problem will be highly appreciated.

Regards,
HY

**Comment by resuna** [comment]
Can you do this on your system:

$ tclsh
% puts $auto_path

**Comment by hongyi-zhao** [comment]
```
$ tclsh
can't find package tclreadline
% puts $auto_path
/usr/share/tcltk/tcl8.6 /usr/share/tcltk /usr/lib /usr/local/lib/tcltk /usr/local/share/tcltk /usr/lib/tcltk/x86_64-linux-gnu /usr/lib/tcltk /usr/lib/tcltk/tcl8.6
% 
```

**Comment by resuna** [comment]
Doesn't include /usr/local/lib so it won't look in /usr/local/lib for packages. Linux doesn't tend to use /usr/local the way BSD does, so it's not surprising that whoever made the tcl package you installed didn't include that.

You could `lappend auto_path /usr/local/lib` in your .tclshrc, or build tclreadline with the default prefix (which it gets from `tclConfig.sh`), or build it with `--prefix=/usr/local --libdir=/usr/local/lib/tcltk`.

**Comment by hongyi-zhao** [comment]
> Is there a particular reason you're installing it BSD-style on Linux?

The packages exist in the distribution's repo will usually be compiled with the `--prefix=/usr`, e.g. the tcl-tclreadline, which is the counterpart of tclreadline, has the following installation locations:

```
$ apt-file list tcl-tclreadline
tcl-tclreadline: /usr/include/x86_64-linux-gnu/tclreadline.h
tcl-tclreadline: /usr/lib/tcltk/x86_64-linux-gnu/tclreadline2.3.8/pkgIndex.tcl
tcl-tclreadline: /usr/lib/tcltk/x86_64-linux-gnu/tclreadline2.3.8/tclreadlineCompleter.tcl
tcl-tclreadline: /usr/lib/tcltk/x86_64-linux-gnu/tclreadline2.3.8/tclreadlineInit.tcl
tcl-tclreadline: /usr/lib/tcltk/x86_64-linux-gnu/tclreadline2.3.8/tclreadlineSetup.tcl
tcl-tclreadline: /usr/lib/x86_64-linux-gnu/libtclreadline-2.3.8.so
tcl-tclreadline: /usr/lib/x86_64-linux-gnu/libtclreadline.so
tcl-tclreadline: /usr/share/doc/tcl-tclreadline/AUTHORS
tcl-tclreadline: /usr/share/doc/tcl-tclreadline/README.md
tcl-tclreadline: /usr/share/doc/tcl-tclreadline/changelog.Debian.gz
tcl-tclreadline: /usr/share/doc/tcl-tclreadline/copyright
tcl-tclreadline: /usr/share/lintian/overrides/tcl-tclreadline
tcl-tclreadline: /usr/share/man/man3/tclreadline.3tcl.gz
```
In order to avoid confliction with the locations used by the packages installed from the distribution's repo, I generally use `--prefix=/usr/local` for self-compiled packages.

Regards,
HY

**Comment by hongyi-zhao** [comment]
See [here](https://groups.google.com/g/comp.lang.tcl/c/BtZvdj-nIZk/m/XdCxVnolDAAJ) for more detailed discussion on this problem.

**Comment by resuna** [comment]
The bottom line:

If you're going to install it in a location that is not standard for your existing Tcl install, you have to tell Tcl to look for it there, or you have to install it in one of the places Tcl is already looking for it. That's all there is. Since you didn't want to change where you were installing it, I was merely suggesting one possible way you could compensate for it since for whatever reason your Tcl install was looking in the subdirectory /usr/local/lib/tcltk. The other possible solution is to add /usr/local/lib to the places it was looking for it.

This has nothing to do with tclreadline. It has to do with the way your Tcl configuration isn't looking in /usr/local/lib for package files.
