### ISSUE TITLE
Problem with "attempt to load the shared-library using a relative path too"

### ISSUE THREAD

**Issue by ericjunkermann** [flightaware/tclreadline#35]
This refers to commit 5ada457 (issue #17).

In _tclreadlineInit.tcl.in_, the line
```
    foreach dirname {@TCLRL_LIBDIR@ [file dirname [info script]]} {
```
the list of values for **dirname** is actually

"@TCLRL_LIBDIR@"  "[file"  "dirname"  "[info"  "script]]"

because, inside the braces, the command substitutions don't happen, so the code will end up
erroring while checking `"script]]"` if the first location fails (the other 3 will fail but not be reported).

The line should, I think, be
```
      foreach dirname [list @TCLRL_LIBDIR@ [file dirname [info script]]] {
```
meaning that the locations checked will be the one from **configure**
and the location of *pkgIndex.tcl* .

**Comment by bovine** [comment]
Thanks for the issue report!
