### ISSUE TITLE
the '!' character can not be used in any tcl command in a  tclreadline shell.

### ISSUE THREAD

**Issue by StefanSchippers** [flightaware/tclreadline#52]
The `!` character is used for history expansion, and thus can not be used as a regular character in tcl commands:
```
tclsh8.6 [~] set a {!}
tclreadline::Loop: error. error in history expansion: !}: event not found

tclsh8.6 [~] expr {!1}
invalid bareword "ls"
in expression "ls";
should be "$ls" or "{ls}" or "ls(...)" or ...
while evaluating expr {ls}
tclsh8.6 [~] 

```
Is there any way to tell tclreadline to avoid interpreting the `!` character?

I know, the character can be escaped, like in:
```
set a "\!"
expr "\!1"
```
but this means I can not copy & paste tcl lines into the tclreadline console.

**Comment by cyanogilvie** [comment]
I turn off history expansion for this reason:
```
tclreadline::readline historyexpansion no
```

**Comment by StefanSchippers** [comment]
That would be great for me. Unfortunately I tried this either at the tclreadline console and in the C initialization code of my project and the answer is the same:
```
[~] tclreadline::readline historyexpansion no
bad option "historyexpansion": must be read, initialize, write, add, complete, customcompleter, builtincompleter, eofchar, reset-terminal, bell, text, or update
while evaluating tclreadline::readline historyexpansion no
```

**Comment by StefanSchippers** [comment]
Looks like a patch exists upstream to disable history expansion. It is simply not packaged for Debian testing. Will try to manually install.

**Comment by bovine** [comment]
> I turn off history expansion for this reason:
> 
> ```
> tclreadline::readline historyexpansion no
> ```

What about if you turn off history expansion?:
```
tclreadline::readline historyexpansion no
```
