### ISSUE TITLE
Please, create new tagged release

### ISSUE THREAD

**Issue by Eloitor** [flightaware/tclreadline#55]
The latest tagged release is old and doesn't include the fix for https://github.com/flightaware/tclreadline/issues/52

**Comment by bovine** [comment]
It would probably be important to get the Github Actions compiling the code and passing the tests again, before I would want to tag a new release. However, you are welcome to use the master branch for your own testing and let us know if you encounter any problems.

**Comment by bovine** [comment]
tests were fixed by issue #56 

we'll be making a new release soon, now that issue #57 was merged.

**Comment by bovine** [comment]
v2.4.0 has been tagged and released.
