### ISSUE TITLE
Bad directory displayed as default prompt

### ISSUE THREAD

**Issue by bovine** [flightaware/tclreadline#6]
The default prompt from tclreadline seems to corrupt the displayed path when in user's home directory:
```
$ tclsh
tclsh8.6 [/usr~/work/firehose_stream] puts "hello"
hello
```

I don't think the “/usr” should be displayed front of my home-directory based path “~/work/firehose_stream”

The above output is from a `~/.tclshrc` that contains simply:
```
if {$tcl_interactive} {package require tclreadline; ::tclreadline::Loop}
```

**Comment by bovine** [comment]
Notably, my entry in /etc/passwd is probably causing this because /home is a symlink to /usr/home

```
jeff.lawson@graceful:~/work/firehose_stream>pwd
/usr/home/jeff.lawson/work/firehose_stream
jeff.lawson@graceful:~/work/firehose_stream>grep jeff.lawson /etc/passwd
jeff.lawson:*:2058:2058:Jeff Lawson:/home/jeff.lawson:/bin/tcsh
```

**Comment by resuna** [comment]
This seems to be the guilty code. Possibly need to replace `$env(HOME)` with a symlink-expanded version?

`                        if [info exists env(HOME)] {
                            regsub $env(HOME) $pwd "~" pwd
                        }
`

**Comment by bovine** [comment]
Maybe also require that the regsub can only happen at the beginning of the string

**Comment by bovine** [comment]
The use of regsub might also have unintended matches if the $env(HOME) contains ".", which has special meaning in a regexp content.

**Comment by snoe925** [comment]
If you set your $HOME to /usr/home/jeff.lawson does tclreadline display the correct prompt?

**Comment by bovine** [comment]
jeff.lawson@graceful:~/work/firehose_stream>tclsh
tclsh8.6 [/usr~/work/firehose_stream]

jeff.lawson@graceful:~/work/firehose_stream>env HOME=/usr/home/jeff.lawson tclsh
tclsh8.6 [~/work/firehose_stream]

**Comment by snoe925** [comment]
This works for me.  A bit odd I agree but the symlink is the problem.
```
 HOME=/usr$HOME tclsh
tclsh8.6 [~]
```

**Comment by bovine** [comment]
Maybe something like this?
```
                        if {[info exists env(HOME)]} {
                            set home [file normalize $env(HOME)]
                            if {[string equal -length [string length $home] $pwd $home]} {
                                set pwd [string replace $pwd 0 [string length $home] "~"]
                            }
                        }
```

**Comment by resuna** [comment]
Yeh, that looks good, but perhaps cache the `[file normalize]`

**Comment by bovine** [comment]
Behavior before:
```
jeff.lawson@hopnu:~/opensource/tclreadline>tclsh
tclsh8.6 [/usr~/opensource/tclreadline]
```
Behavior now:
```
jeff.lawson@hopnu:~/opensource/tclreadline>tclsh
tclsh8.6 [~/opensource/tclreadline]
```
