### ISSUE TITLE
Dangled symlinks INSTALL and aux/*

### ISSUE THREAD

**Issue by sgolovan** [flightaware/tclreadline#7]
Hi!

The sources currently have a few symlinks (namely INSTALL and also aux/compile, aux/config.guess, aux/config.sub, aux/depcomp, aux/install-sh, aux/ltmain.sh and aux/missing) which point somewhere inside /usr/local/share/automake-1.15. It's a bit inconvenient to have them, especially if I don't have automake-1.15 installed in /usr/local. Can you remove them (replace by actual files)?

**Comment by bovine** [comment]
Done, thanks.
